name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: ^0.18.3
  flutter_fadein: ^2.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/download.jpg
    - assets/images/sbulogo.jpg
    - assets/images/drbicon.jpg
    - assets/images/1200px-Stony_Brook_U_logo_vertical.png
    - assets/audios/Success in Mind - Intro - Board 1.mp3
    - assets/audios/Success in Mind- Description - Board 2.mp3
    - assets/audios/Tutorial Board 1 Audio.mp3
    - assets/audios/Tutorial Board 2 Audio.mp3
    - assets/audios/Tutorial Board 3 Audio.mp3
    - assets/audios/Tutorial Board 4 Audio.mp3
    - assets/audios/Tutorial Board 5 Audio.mp3
    - assets/audios/Tutorial Board 6 Audio.mp3
    - assets/audios/Tutorial Board 7 Audio.mp3
    - assets/audios/Tutorial Board 8 Audio.mp3
    - assets/audios/Tutorial Board 9 Audio.mp3