name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: ^0.18.3
  flutter_fadein: ^2.0.0
  url_launcher: ^6.0.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  screenshot: ^0.3.0
  share: ^0.6.5+4
  fl_chart: ^0.36.1
  flutter_svg: ^0.22.0
  badges: ^1.2.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/download.jpg
    - assets/images/sbulogo.jpg
    - assets/images/drbicon.jpg
    - assets/images/my well.jpg
    - assets/images/1200px-Stony_Brook_U_logo_vertical.png
    - assets/images/yes.svg
    - assets/images/wrong.svg
    - assets/audios/Success in Mind - Intro - Board 1.mp3
    - assets/audios/Success in Mind- Description - Board 2.mp3
    - assets/audios/Tutorial Board 1 Audio.mp3
    - assets/audios/Tutorial Board 2 Audio.mp3
    - assets/audios/Tutorial Board 3 Audio.mp3
    - assets/audios/Tutorial Board 4 Audio.mp3
    - assets/audios/Tutorial Board 5 Audio.mp3
    - assets/audios/Tutorial Board 6 Audio.mp3
    - assets/audios/Tutorial Board 7 Audio.mp3
    - assets/audios/Tutorial Board 8 Audio.mp3
    - assets/audios/Tutorial Board 9 Audio.mp3
    - assets/audios/Tutorial Board 10 Audio.mp3
    - assets/audios/Tutorial Board 11 Audio.mp3
    - assets/audios/Tutorial Board 12 Audio.mp3
    - assets/audios/Tutorial Board 13 Audio.mp3
    - assets/audios/Tutorial Board 14 Audio.mp3
    - assets/audios/Tutorial Board 15 Audio.mp3